<?php
    /**
    *
    * @name:       iPhone 5 Emulator
    * @version:    0.1.0
    * @author:     EOussama
    * @license     MIT
    * @source:     https://github.com/EOussama/iPhone 5 Emulator
    * 
    */
?>

<!DOCTYPE html>

<html lang="en">
    <head>

        <!-- Meta data. -->
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	    <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="EOussama">
        <meta name="application-name" content="iPhone 5 Emulator">
        <meta name="description" content="Auto generated with Estrap.">
        <meta name="keywords" content="webapp, estrap">

        <!-- The main stylesheets. -->
        <link rel="stylesheet" href="assets/css/main.css">

        <!-- The favicon. -->
        <link rel="shortcut icon" type="image/png" href="assets/img/favicon.png">

        <!-- The title. -->
        <title>iPhone 5 Emulator</title>
    </head>

    <body>

        <!-- The main content. -->
        <main>
            <h1>iPhone 5 Emulator</h1>
            <p>Generated by Estrap</p>
        </main>

        <!-- The main javascript file. -->
        <script src="assets/js/main.js"></script>
    </body>
</html>
