#!/usr/bin/bash

# -----------------------------------------------------------
#
# @name:        Estrap
# @version:     0.5.0
# @author:      EOussama
# @source:      https://github.com/EOussama/web-env-setup
# @license:     Apache-2.0
#
# -----------------------------------------------------------



# Shows a message and pauses the script.
Pause() {
    echo "[Estrap] $1"
    read -p "Press any key in order to continue: "
}

# Creates a folder.
CreateFolder() {
    if [ ! -e "$1/$2" ]
    then
        mkdir "$1/$2"
    fi
}

# Creates a file.
CreateFile() {
    touch "$1/$2/$3"
    echo "$4" >> "$1/$2/$3"
}

# Populates a file with some html content.
PopulateHTML() {
    echo -e '<!--

    @name:       '"$PROJECT_NAME"'
    @version:    0.1.0
    @author:     '"$AUTHOR"'
    @license     '"$LICENSE"'
    @source:     github.com/EOussama/'"$PROJECT_NAME"'
    
-->
<!DOCTYPE html>

<html lang="en">
    <head>

        <!-- Meta data. -->
        <meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="'"$AUTHOR"'">
        <meta name="application-name" content="'"$PROJECT_NAME"'">
        <meta name="description" content="'"$PROJECT_DESCRIPTION"'">
        <meta name="keywords" content="'"$PROJECT_KEYWORDS"'">

        <!-- The main stylesheets. -->
        <link rel="stylesheet" href="assets/css/main.css">

        <!-- The favicon. -->
        <link rel="shortcut icon" type="image/png" href="assets/img/favicon.png">

        <!-- The title. -->
        <title>'"$PROJECT_NAME"'</title>
    </head>

    <body>

        <!-- The main content. -->
        <main>
            <h1>'"$PROJECT_NAME"'</h1>
            <p>Generated by Estrap</p>
        </main>

        <!-- The main javascript file. -->
        <script src="assets/js/main.js"></script>
    </body>
</html>' > "$1"
}

# Populates a file with some php content.
PopulatePHP() {
    echo -e '<?php
    /**
    *
    * @name:       '"$PROJECT_NAME"'
    * @version:    0.1.0
    * @author:     '"$AUTHOR"'
    * @license     '"$LICENSE"'
    * @source:     github.com/EOussama/'"$PROJECT_NAME"'
    * 
    */
?>

<!DOCTYPE html>

<html lang="en">
    <head>

        <!-- Meta data. -->
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="'"$AUTHOR"'">
        <meta name="application-name" content="'"$PROJECT_NAME"'">
        <meta name="description" content="'"$PROJECT_DESCRIPTION"'">
        <meta name="keywords" content="'"$PROJECT_KEYWORDS"'">

        <!-- The main stylesheets. -->
        <link rel="stylesheet" href="assets/css/main.css">

        <!-- The favicon. -->
        <link rel="shortcut icon" type="image/png" href="assets/img/favicon.png">

        <!-- The title. -->
        <title>'"$PROJECT_NAME"'</title>
    </head>

    <body>

        <!-- The main content. -->
        <main>
            <h1>'"$PROJECT_NAME"'</h1>
            <p>Generated by Estrap</p>
        </main>

        <!-- The main javascript file. -->
        <script src="assets/js/main.js"></script>
    </body>
</html>' > "$1"
}

# Populates a file with some javascript content.
PopulateJS() {
    echo -e '/**
*
* @name:       '"$PROJECT_NAME"'
* @version:    0.1.0
* @author:     '"$AUTHOR"'
* @license     '"$LICENSE"'
* @source:     github.com/EOussama/'"$PROJECT_NAME"'
* 
* The main javascript file of the app.
*/

window.addEventListener('"'"'load'"'"', () => {
    console.log('"'"'Hello, world!'"'"');
});' > "$1"
}

# Populates a file with some css content.
PopulateCSS() {
    echo -e '/**
*
* @name:       '"$PROJECT_NAME"'
* @version:    0.1.0
* @author:     '"$AUTHOR"'
* @license     '"$LICENSE"'
* @source:     github.com/EOussama/'"$PROJECT_NAME"'
* 
* The main stylesheet of the app.
*/

body {
    font-family: Arial, Helvetica, sans-serif;
}

main {
    padding: 50px 80px;
}' > "$1"
}

# Populates a file with some node content.
PopulateNode() {
    echo -e '/**
*
* @name:       '"$PROJECT_NAME"'
* @version:    0.1.0
* @author:     '"$AUTHOR"'
* @license     '"$LICENSE"'
* @source:     github.com/EOussama/'"$PROJECT_NAME"'
* 
* The main entry of the app.
*/

const http = require('"'"'http'"'"');

http.createServer((req, res) => {
    res.writeHead(200, {'"'"'Content-Type'"'"': '"'"'text/plain'"'"'});
    res.end('"'"'Hello, world!'"'"');
}).listen(8080);' > "$1"
}



# The directory of the bash script.
ESTRAP_PATH=`dirname $BASH_SOURCE`

# The current directory.
CURRENT_PATH=$(pwd)

# The project's name.
PROJECT_NAME=$1

# The template's name.
TEMPLATE_NAME=$2

# The author's name.
AUTHOR=EOussama

# The project's license.
LICENSE=MIT

# The author's name.
PROJECT_DESCRIPTION="Auto generated with Estrap."

# The author's name.
PROJECT_KEYWORDS="webapp, estrap"




# Creating the templates' folder.
CreateFolder $ESTRAP_PATH "templates"

# Creating the html template.
CreateFolder $ESTRAP_PATH "templates/html"
CreateFolder $ESTRAP_PATH "templates/html/assets"
CreateFolder $ESTRAP_PATH "templates/html/assets/js"
CreateFolder $ESTRAP_PATH "templates/html/assets/css"
CreateFolder $ESTRAP_PATH "templates/html/assets/img"
CreateFile $ESTRAP_PATH "templates/html" "index.html" ""
CreateFile $ESTRAP_PATH "templates/html/assets/js" "main.js" ""
CreateFile $ESTRAP_PATH "templates/html/assets/css" "main.css" ""
PopulateHTML "$ESTRAP_PATH/templates/html/index.html"
PopulateJS "$ESTRAP_PATH/templates/html/assets/js/main.js"
PopulateCSS "$ESTRAP_PATH/templates/html/assets/css/main.css"
cp -R "$ESTRAP_PATH/resources/img/favicon.png" "$ESTRAP_PATH/templates/html/assets/img"

# Creating the php template.
CreateFolder $ESTRAP_PATH "templates/php"
CreateFolder $ESTRAP_PATH "templates/php/config"
CreateFolder $ESTRAP_PATH "templates/php/controllers"
CreateFolder $ESTRAP_PATH "templates/php/helpers"
CreateFolder $ESTRAP_PATH "templates/php/lib"
CreateFolder $ESTRAP_PATH "templates/php/models"
CreateFolder $ESTRAP_PATH "templates/php/process"
CreateFolder $ESTRAP_PATH "templates/php/public"
CreateFolder $ESTRAP_PATH "templates/php/public/assets"
CreateFolder $ESTRAP_PATH "templates/php/public/assets/js"
CreateFolder $ESTRAP_PATH "templates/php/public/assets/css"
CreateFolder $ESTRAP_PATH "templates/php/public/assets/img"
CreateFolder $ESTRAP_PATH "templates/php/public/views"
CreateFolder $ESTRAP_PATH "templates/php/templates"
CreateFolder $ESTRAP_PATH "templates/php/templates/partials"
CreateFile $ESTRAP_PATH "templates/php" ".htaccess" ""
CreateFile $ESTRAP_PATH "templates/php/config" "config.ini" ""
CreateFile $ESTRAP_PATH "templates/php/config" "config.php" ""
CreateFile $ESTRAP_PATH "templates/php/public" "index.php" ""
CreateFile $ESTRAP_PATH "templates/php/public/assets/js" "main.js" ""
CreateFile $ESTRAP_PATH "templates/php/public/assets/css" "main.css" ""
PopulatePHP "$ESTRAP_PATH/templates/php/public/index.php"
PopulateJS "$ESTRAP_PATH/templates/php/public/assets/js/main.js"
PopulateCSS "$ESTRAP_PATH/templates/php/public/assets/css/main.css"
cp -R "$ESTRAP_PATH/resources/img/favicon.png" "$ESTRAP_PATH/templates/php/public/assets/img"

# Creating the node template.
CreateFolder $ESTRAP_PATH "templates/node"
CreateFolder $ESTRAP_PATH "templates/node/models"
CreateFolder $ESTRAP_PATH "templates/node/public"
CreateFolder $ESTRAP_PATH "templates/node/public/assets"
CreateFolder $ESTRAP_PATH "templates/node/public/assets/js"
CreateFolder $ESTRAP_PATH "templates/node/public/assets/css"
CreateFolder $ESTRAP_PATH "templates/node/public/assets/img"
CreateFolder $ESTRAP_PATH "templates/node/views"
CreateFolder $ESTRAP_PATH "templates/node/views/partials"
CreateFile $ESTRAP_PATH "templates/node" "app.js" ""
CreateFile $ESTRAP_PATH "templates/node/public/assets/js" "main.js" ""
CreateFile $ESTRAP_PATH "templates/node/public/assets/css" "main.css" ""
PopulateNode "$ESTRAP_PATH/templates/node/app.js"
PopulateJS "$ESTRAP_PATH/templates/node/public/assets/js/main.js"
PopulateCSS "$ESTRAP_PATH/templates/node/public/assets/css/main.css"
cp -R "$ESTRAP_PATH/resources/img/favicon.png" "$ESTRAP_PATH/templates/node/public/assets/img"

# Check if the project's name is passed.
if [ -z "$PROJECT_NAME" ] || [ -z "$TEMPLATE_NAME" ]
then
    Pause "Usage: estrap [project name] [template name]"
else
    # Check if the template exists.
    if [ -e "$ESTRAP_PATH/templates/$TEMPLATE_NAME" ]
    then
        # Creating the project's folder.
        CreateFolder $CURRENT_PATH $PROJECT_NAME

        # Copying the template.
        cp -R "$ESTRAP_PATH/templates/$TEMPLATE_NAME/." "$CURRENT_PATH/$PROJECT_NAME"

        # Displaying the end message.
        Pause "“$PROJECT_NAME” was successfully created!"
    else
        Pause "The template “$TEMPLATE_NAME” doesn't exist."
    fi
fi
